


CREATE TABLE "ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(32) NOT NULL
);

CREATE TABLE "ganres" (
  "id" integer PRIMARY KEY NOT NULL,
  "name" varchar(32) NOT NULL
);

CREATE TABLE "films" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(64) NOT NULL,
  "description" varchar(200) NOT NULL,
  "release_date" timestamp(date) NOT NULL,
  "duration" integer NOT NULL,
  "rating_id" integer
);

CREATE TABLE "film_genres" (
  "film_id" integer NOT NULL,
  "genre_id" integer NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "login" varchar(64) NOT NULL,
  "name" varchar(64),
  "email" timestamp(64) NOT NULL,
  "birthday" date
);

CREATE TABLE "friends" (
  "user_id" integer NOT NULL,
  "friend_id" integer NOT NULL
);

CREATE TABLE "likes" (
  "film_id" integer NOT NULL,
  "user_id" integer NOT NULL
);

ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "ratings" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "ganres" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");
